import fs from 'node:fs';
import path from 'node:path';

const repoRoot = path.resolve(process.cwd());
const mobileConfigPath =
  process.argv[2] ??
  path.join(repoRoot, 'config', 'env.local.json');

if (!fs.existsSync(mobileConfigPath)) {
  console.error(`[sync-web-env] Missing ${mobileConfigPath}`);
  console.error(`[sync-web-env] Create it by copying config/env.local.json.example → config/env.local.json`);
  process.exit(1);
}

const cfg = JSON.parse(fs.readFileSync(mobileConfigPath, 'utf8'));

const mapping = {
  BACKEND_BASE_URL: 'VITE_BACKEND_BASE_URL',
  BACKEND_API_KEY: 'VITE_BACKEND_API_KEY',
  GOOGLE_WEB_CLIENT_ID: 'VITE_GOOGLE_WEB_CLIENT_ID',

  FIREBASE_API_KEY: 'VITE_FIREBASE_API_KEY',
  FIREBASE_AUTH_DOMAIN: 'VITE_FIREBASE_AUTH_DOMAIN',
  FIREBASE_PROJECT_ID: 'VITE_FIREBASE_PROJECT_ID',
  FIREBASE_STORAGE_BUCKET: 'VITE_FIREBASE_STORAGE_BUCKET',
  FIREBASE_MESSAGING_SENDER_ID: 'VITE_FIREBASE_MESSAGING_SENDER_ID',
  FIREBASE_APP_ID: 'VITE_FIREBASE_APP_ID',
};

const lines = [
  '# AUTO-GENERATED by scripts/sync-web-env.mjs',
  '# Source: config/env.local.json',
  '',
];

for (const [fromKey, toKey] of Object.entries(mapping)) {
  const v = cfg[fromKey];
  if (typeof v === 'string' && v.length) {
    // Basic escaping for newlines (shouldn't exist in these vars)
    lines.push(`${toKey}=${v.replace(/\n/g, '\\n')}`);
  } else {
    lines.push(`# ${toKey}=`);
  }
}

lines.push('');

const outPath = path.join(repoRoot, 'apps', 'web', '.env.local');
fs.writeFileSync(outPath, lines.join('\n'), 'utf8');
console.log(`[sync-web-env] wrote ${path.relative(repoRoot, outPath)}`);


